/*
  H2 DB DATA 생성
  1) BOARD
  2) COMMENT
*/

-- BOARD
INSERT INTO BOARD
(
  SUBJECT, 
  CONTENT, 
  THUMNAIL,
  CREATED_DATE,
  UPDATED_DATE, 
  DELETED_YN
) 
VALUES
(
  '개행이 들어간 글', 
  '1번 테스트글은 
  개행 테스트 글입니다.
  
  아자뵤',
  '955329324.jpeg',
  NOW(),
  NOW(),
  FALSE
);
INSERT INTO BOARD(SUBJECT, CONTENT, CREATED_DATE, DELETED_YN) VALUES('제목', '내용', NOW(), FALSE);
INSERT INTO BOARD(SUBJECT, CONTENT, CREATED_DATE, DELETED_YN) VALUES('제목', '내용', NOW(), FALSE);


-- COMMENT
INSERT INTO COMMENT(BOARD_NO, COMMENT, CREATED_DATE, DELETED_YN) VALUES(1, '1번째 댓글', NOW(), FALSE);
INSERT INTO COMMENT(BOARD_NO, COMMENT, CREATED_DATE, DELETED_YN) VALUES(1, '2번째 댓글', NOW(), FALSE);
INSERT INTO COMMENT(BOARD_NO, COMMENT, CREATED_DATE, DELETED_YN) VALUES(1, '3번째 댓글', NOW(), FALSE);
INSERT INTO COMMENT(BOARD_NO, COMMENT, CREATED_DATE, DELETED_YN) VALUES(1, '4번째 댓글', NOW(), FALSE);