/*
  H2 DB TABLE 생성
  1) BOARD
  2) COMMENT
*/

CREATE TABLE BOARD
(
  NO INT AUTO_INCREMENT PRIMARY KEY,
  SUBJECT VARCHAR(255),
  CONTENT VARCHAR(500),
  CREATED_DATE DATETIME,
  UPDATED_DATE DATETIME,
  DELETED_YN BOOLEAN
);

CREATE TABLE COMMENT
(
  NO INT AUTO_INCREMENT PRIMARY KEY, 
  BOARD_NO INT,
  COMMENT VARCHAR(500),
  CREATED_DATE DATETIME,
  UPDATED_DATE DATETIME,
  DELETED_YN BOOLEAN
);